BATCH_SIZE: 256
BETA: 0.01
CLINIC_PARAM:
- CANCER_TYPE_ACRONYM
- TMB_NONSYNONYMOUS
- AGE
- SEX
- AJCC_PATHOLOGIC_TUMOR_STAGE_SHORT
- OS_STATUS
- OS_MONTHS
- DFS_STATUS
- PFS_STATUS
- MSI_SCORE_MANTIS
- ANEUPLOIDY_SCORE
- TUMOR_TISSUE_SITE'
- GRADE
- SUBTYPE
CLUSTER_ALG: HDBScan
CLUSTER_N: 32
DATA_TYPE:
  ANNO:
    FILE_RAW: cf_clinical_data_formatted.parquet
    TYPE: ANNOTATION
  RNA:
    FILE_RAW: cf_formatted.parquet
    FILTERING: Var
    SCALING: Standard
    TYPE: NUMERIC
DIM_RED_METH: UMAP
EPOCHS: 300
#FIX_RANDOMNESS: all
#GLOBAL_SEED: 42
K_FILTER: 6000
LATENT_DIM_FIXED: 16
LR_FIXED: 0.001
MIN_CLUSTER_N: 20
ML_ALG:
- Linear
ML_SPLIT: use-split
ML_TASKS:
- PCA
ML_TYPE: Auto-detect
MODEL_TYPE: varix
PLOT_CLUSTLATENT: true
PLOT_WEIGHTS: true
PREDICT_SPLIT: all
RECONSTR_LOSS: MSE
SPLIT:
- 0.6
- 0.2
- 0.2
TRAIN_TYPE: train
VAE_LOSS: KL
SAMPLE_SIGNAL: data/raw/sample_list_male.txt
FEATURE_SIGNAL: data/raw/feature_list_10_base1.txt
SIGNAL_STRENGTH: 0.9
APPLY_SIGNAL: true


RUN_ID: ridge_plot
