BATCH_SIZE: 256
BETA: 0.01
CLINIC_PARAM:
- CANCER_TYPE_ACRONYM
- TMB_NONSYNONYMOUS
- AGE
- SEX
- AJCC_PATHOLOGIC_TUMOR_STAGE_SHORT
- OS_STATUS
- OS_MONTHS
- DFS_STATUS
- PFS_STATUS
- MSI_SCORE_MANTIS
- ANEUPLOIDY_SCORE
- TUMOR_TISSUE_SITE
- GRADE
- SUBTYPE
CLUSTER_ALG: HDBScan
CLUSTER_N: 32
DATA_TYPE:
  ANNO:
    FILE_RAW: data_clinical_formatted.parquet
    TYPE: ANNOTATION
  RNA:
    FILE_RAW: data_mrna_seq_v2_rsem_formatted.parquet
    FILTERING: Var
    SCALING: Standard
    TYPE: NUMERIC
  METH:
    FILE_RAW: "data_methylation_per_gene_formatted.parquet"
    TYPE: "NUMERIC"
    SCALING: "Standard"
    FILTERING: "Var"
  MUT:
    FILE_RAW: "data_combi_MUT_CNA_formatted.parquet"
    FILTERING: Var
    SCALING: Standard
    TYPE: NUMERIC
DIM_RED_METH: UMAP
EPOCHS: 300
K_FILTER: 2000
LATENT_DIM_FIXED: 16
LR_FIXED: 0.001
MIN_CLUSTER_N: 20
ML_ALG:
- Linear
ML_SPLIT: use-split
ML_TASKS:
- PCA
ML_TYPE: Auto-detect
MODEL_TYPE: varix
PLOT_CLUSTLATENT: true
PLOT_WEIGHTS: true
PREDICT_SPLIT: all
RECONSTR_LOSS: MSE
SPLIT:
- 0.6
- 0.2
- 0.2
TRAIN_TYPE: train
VAE_LOSS: KL


RUN_ID: tcga_001_16dim
